# ALL CONSTANTS SETUP HERE

# CONSTANTS 
MAX_CAR = 5
TOTAL_SLOTS = 5

# PIN SETUP
# COUNTER PIN SETUP
AIR_ENTRY_PIN       = None
AIR_EXIT_PIN        = None

SERVO_ENTRY_PIN     = None
SERVO_EXIT_PIN      = None

I2C_SCL_ENTRY_PIN   = 26
I2C_SCL_EXIT_PIN    = 26

I2C_SDA_ENTRY_PIN   = 27
I2C_SDA_EXIT_PIN    = 27

# ULTRASONIC SETUP
TRIG_PIN_1 = None
ECHO_PIN_1 = None
TRIG_PIN_2 = None
ECHO_PIN_2 = None
TRIG_PIN_3 = None
ECHO_PIN_3 = None
TRIG_PIN_4 = None
ECHO_PIN_4 = None
TRIG_PIN_5 = None
ECHO_PIN_5 = None

# ULTRASONIC CONFIGS
INITIAL_STATUS      = 0
DISTANCE_THRESHOLD  = 15 # in cm
STABLE_LIMIT        = 5

# LED SETUP
LED_PIN_1 = None
LED_PIN_2 = None
LED_PIN_3 = None
LED_PIN_4 = None
LED_PIN_5 = None

# DEBUG SETUP
def Debug(msg):
    print(f"[DEBUGGER]: {msg}")